--Create Vehicles
INSERT INTO VEHICLES(TYPE, NAME, WHEELS, SEATS, MUSIC_SYSTEM, BOOSTER, HYDRAULIC_SYSTEM) VALUES('NC','Kia-Seltos', 4, 5, TRUE, FALSE, FALSE);
INSERT INTO VEHICLES(TYPE, NAME, WHEELS, SEATS, MUSIC_SYSTEM, BOOSTER, HYDRAULIC_SYSTEM) VALUES('SC','Kia-test', 4, 5, TRUE, TRUE, FALSE);
INSERT INTO VEHICLES(TYPE, NAME, WHEELS, SEATS, MUSIC_SYSTEM, BOOSTER, HYDRAULIC_SYSTEM) VALUES('TT','test', 10, null, TRUE, FALSE, FALSE);
INSERT INTO VEHICLES(TYPE, NAME, WHEELS, SEATS, MUSIC_SYSTEM, BOOSTER, HYDRAULIC_SYSTEM) VALUES('MT','Test company', 10, null, TRUE, FALSE, TRUE);




--INSERT INTO VEHICLES(TYPE, NAME, WHEELS, SEATS, MUSIC_SYSTEM, BOOSTER, HYDRAULIC_SYSTEM) VALUES('Normal Car','Kia-Seltos', 4, 5, TRUE, FALSE, FALSE);
--INSERT INTO VEHICLES(TYPE, NAME, WHEELS, SEATS, MUSIC_SYSTEM, BOOSTER, HYDRAULIC_SYSTEM) VALUES('Normal Car','Kia-Seltos', 4, 5, TRUE, FALSE, FALSE);
--INSERT INTO VEHICLES(TYPE, NAME, WHEELS, SEATS, MUSIC_SYSTEM, BOOSTER, HYDRAULIC_SYSTEM) VALUES('Normal Car','Kia-Seltos', 4, 5, TRUE, FALSE, FALSE);
--INSERT INTO VEHICLES(TYPE, NAME, WHEELS, SEATS, MUSIC_SYSTEM, BOOSTER, HYDRAULIC_SYSTEM) VALUES('Normal Car','Kia-Seltos', 4, 5, TRUE, FALSE, FALSE);
--INSERT INTO VEHICLES(TYPE, NAME, WHEELS, SEATS, MUSIC_SYSTEM, BOOSTER, HYDRAULIC_SYSTEM) VALUES('Normal Car','Kia-Seltos', 4, 5, TRUE, FALSE, FALSE);
--INSERT INTO VEHICLES(TYPE, NAME, WHEELS, SEATS, MUSIC_SYSTEM, BOOSTER, HYDRAULIC_SYSTEM) VALUES('Normal Car','Kia-Seltos', 4, 5, TRUE, FALSE, FALSE);
--INSERT INTO VEHICLES(TYPE, NAME, WHEELS, SEATS, MUSIC_SYSTEM, BOOSTER, HYDRAULIC_SYSTEM) VALUES('Normal Car','Kia-Seltos', 4, 5, TRUE, FALSE, FALSE);
--INSERT INTO VEHICLES(TYPE, NAME, WHEELS, SEATS, MUSIC_SYSTEM, BOOSTER, HYDRAULIC_SYSTEM) VALUES('Normal Car','Kia-Seltos', 4, 5, TRUE, FALSE, FALSE);
--INSERT INTO VEHICLES(TYPE, NAME, WHEELS, SEATS, MUSIC_SYSTEM, BOOSTER, HYDRAULIC_SYSTEM) VALUES('Normal Car','Kia-Seltos', 4, 5, TRUE, FALSE, FALSE);


