CREATE TABLE VEHICLES(
ID IDENTITY NOT NULL PRIMARY KEY,
TYPE VARCHAR(255) NOT NULL,
NAME VARCHAR(255) NOT NULL UNIQUE,
WHEELS INT NOT NULL,
SEATS INT,
MUSIC_SYSTEM BOOLEAN DEFAULT FALSE,
BOOSTER BOOLEAN DEFAULT FALSE,
HYDRAULIC_SYSTEM BOOLEAN DEFAULT FALSE
);